In [ ]:
import pandas as pd
df = pd.read_csv('data\\raw\\combined_data.csv')
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AAED255E1310E516,classic_bike,2025-10-27 08:19:53.208,2025-10-27 08:25:53.481,Wells St & Polk St,CHI00606,Franklin St & Washington St,CHI02074,41.872732,-87.633516,41.883180,-87.635110,member
1,F90C86BF3BB85040,classic_bike,2025-10-14 07:42:55.465,2025-10-14 08:04:08.663,Racine Ave & Wrightwood Ave,CHI00506,McClurg Ct & Ohio St,CHI00330,41.928887,-87.658971,41.892592,-87.617289,member
2,90429D9729A3EE8E,classic_bike,2025-10-12 08:18:23.613,2025-10-12 08:28:38.983,Clinton St & 18th St,CHI00235,Desplaines St & Jackson Blvd,CHI00518,41.857950,-87.640826,41.878119,-87.643948,casual
3,C8433F9B78A1E63D,electric_bike,2025-10-14 07:45:56.471,2025-10-14 08:07:24.447,Pine Grove Ave & Irving Park Rd,CHI00482,Wells St & Huron St,CHI00294,41.954398,-87.647997,41.894795,-87.634374,member
4,62F3C413C442C154,electric_bike,2025-10-19 10:08:45.138,2025-10-19 10:12:34.771,Pine Grove Ave & Irving Park Rd,CHI00482,Sheridan Rd & Montrose Ave,CHI00290,41.954365,-87.647929,41.961670,-87.654640,member

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6171785 entries, 0 to 6171784
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), str(9)
memory usage: 612.1 MB

In [7]:
df.shape

(6171785, 13)

In [8]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])
df['ride_length'] = df['ended_at'] - df['started_at']

In [9]:
df['ride_length'] = df['ride_length'].apply(
    lambda x: f"{int(x.total_seconds() // 3600):02d}:{int((x.total_seconds() % 3600) // 60):02d}:{int(x.total_seconds() % 60):02d}"
)

In [10]:
df['day_of_week'] = df['started_at'].dt.day_name()

In [11]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,AAED255E1310E516,classic_bike,2025-10-27 08:19:53.208,2025-10-27 08:25:53.481,Wells St & Polk St,CHI00606,Franklin St & Washington St,CHI02074,41.872732,-87.633516,41.883180,-87.635110,member,00:06:00,Monday
1,F90C86BF3BB85040,classic_bike,2025-10-14 07:42:55.465,2025-10-14 08:04:08.663,Racine Ave & Wrightwood Ave,CHI00506,McClurg Ct & Ohio St,CHI00330,41.928887,-87.658971,41.892592,-87.617289,member,00:21:13,Tuesday
2,90429D9729A3EE8E,classic_bike,2025-10-12 08:18:23.613,2025-10-12 08:28:38.983,Clinton St & 18th St,CHI00235,Desplaines St & Jackson Blvd,CHI00518,41.857950,-87.640826,41.878119,-87.643948,casual,00:10:15,Sunday
3,C8433F9B78A1E63D,electric_bike,2025-10-14 07:45:56.471,2025-10-14 08:07:24.447,Pine Grove Ave & Irving Park Rd,CHI00482,Wells St & Huron St,CHI00294,41.954398,-87.647997,41.894795,-87.634374,member,00:21:27,Tuesday
4,62F3C413C442C154,electric_bike,2025-10-19 10:08:45.138,2025-10-19 10:12:34.771,Pine Grove Ave & Irving Park Rd,CHI00482,Sheridan Rd & Montrose Ave,CHI00290,41.954365,-87.647929,41.961670,-87.654640,member,00:03:49,Sunday

In [12]:
df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
ride_id,6171785,6171750,D582320F33836B82,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rideable_type,6171785,2,electric_bike,4387353,NaN,NaN,NaN,NaN,NaN,NaN,NaN
started_at,6171785,NaN,NaN,NaN,2026-05-10 00:43:01.086364,2025-09-30 08:37:53.455000,2026-03-08 14:28:31.431000,2026-06-07 22:57:19.972000,2026-08-04 17:36:48.071000,2026-09-30 23:59:38.090000,NaN
ended_at,6171785,NaN,NaN,NaN,2026-05-10 00:58:13.439078,2025-10-01 00:00:07.199000,2026-03-08 14:47:28.120000,2026-06-07 23:16:34.676000,2026-08-04 17:51:50.203000,2026-09-30 23:59:48.043000,NaN
start_station_name,4882299,1989,Navy Pier,66588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_station_id,4882299,1988,CHI01747,66588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
end_station_name,4816298,2025,Navy Pier,65854,NaN,NaN,NaN,NaN,NaN,NaN,NaN
end_station_id,4816298,2025,CHI01747,65854,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_lat,6171785.0,NaN,NaN,NaN,41.904583,41.64,41.882752,41.9,41.93,42.07,0.044268
start_lng,6171785.0,NaN,NaN,NaN,-87.646934,-87.91,-87.66,-87.642884,-87.63,-87.52,0.026953
end_lat,6166334.0,NaN,NaN,NaN,41.904974,41.51,41.882906,41.9,41.93,42.19,0.044441
end_lng,6166334.0,NaN,NaN,NaN,-87.647292,-88.1,-87.66,-87.643118,-87.63,-87.37,0.027212
member_casual,6171785,2,member,3982761,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ride_length,6171785,18841,00:04:37,7709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day_of_week,6171785,7,Saturday,974296,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1289486
start_station_id      1289486
end_station_name      1355487
end_station_id        1355487
start_lat                   0
start_lng                   0
end_lat                  5451
end_lng                  5451
member_casual               0
ride_length                 0
day_of_week                 0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(35)

In [15]:
df.drop_duplicates(keep='first', inplace=True)
print(df.duplicated().sum())

0

In [16]:
df['start_station_name'].isnull().sum()/len(df)*100

np.float64(20.893263661036173)

In [17]:
df['end_station_name'].isnull().sum()/len(df)*100

np.float64(21.962538988131406)

In [18]:
df['end_lat'].isnull().sum()/len(df)*100

np.float64(0.08822457163689391)

In [19]:
df.dropna(subset=['end_lat','end_lng'], inplace=True)
print(df[['end_lat','end_lng']].isnull().sum())

end_lat    0
end_lng    0
dtype: int64

In [20]:
df['start_station_name'] = df['start_station_name'].fillna(df['start_station_name'].mode()[0])
df['end_station_name'] = df['end_station_name'].fillna(df['end_station_name'].mode()[0])
df['end_station_id'] = df['end_station_id'].fillna(df['end_station_id'].mode()[0])
df['start_station_id'] = df['start_station_id'].fillna(df['start_station_id'].mode()[0])
df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
ride_length           0
day_of_week           0
dtype: int64

In [22]:
df.to_csv('data\\clean\\cleaned_data.csv', index=False)